### ISSUE TITLE
Reading .yaml configuration from classpath using current threads classloader

### ISSUE THREAD

**Issue by svendiedrichsen** [ivargrimstad/snoop#20]
The SnoopProducer reads the config .yaml file from classpath by using this.getClass().getClassloader() which IMHO is not appropriate within JEE. This should be done by using the current threads classloader. This way you don't make any assumptions whether the classloader which loaded the SnoopProducer is still available for loading the config.

Please see: http://jeecookbook.blogspot.de/2013/07/java-why-you-should-not-use.html

**Comment by ivargrimstad** [comment]
Thanks @svendiedrichsen
